apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: azure-storage-demo
  namespace: default
spec:
  clusterServiceClassExternalName: azure-storage-blob-storage-account-and-container
  clusterServicePlanExternalName: all-in-one
  parameters:
    location: eastus
    resourceGroup: osba-azure-storag-demo
