apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: azure-storage-binding
  namespace: default
spec:
  instanceRef:
    name: azure-storage-demo
  secretName: osba-azure-storag-demo
